"""
02_dataclasses_basics.py
=========================
Demonstrates the @dataclass decorator:
  - A regular class written by hand vs the same class as a dataclass
  - Auto-generated __init__, __repr__, and __eq__
  - How dataclasses reduce boilerplate without hiding behaviour

Run:
    python day-02/02_dataclasses_basics.py
"""

from dataclasses import dataclass


# ══════════════════════════════════════════════════════════════════════════════
# PART 1: Regular class — written by hand
#
# Count the lines needed just for a container of 4 fields:
#   - 6-line __init__   (assign every field)
#   - 8-line __repr__   (format every field)
#   - 8-line __eq__     (compare every field)
# = 22 lines of pure boilerplate that carries zero business logic.
# Every new field requires an edit in all three methods.
# @dataclass replaces all of this with a single class-body declaration.
# ══════════════════════════════════════════════════════════════════════════════

class PipelineConfigManual:
    """A data-holding class written entirely by hand.

    This is the baseline — everything here is pure structural boilerplate.
    There is no business logic at all. All four methods exist purely to
    make the class behave like a well-behaved value object.
    """

    def __init__(self, name: str, source: str, destination: str, parallelism: int = 4):
        self.name = name
        self.source = source
        self.destination = destination
        self.parallelism = parallelism

    def __repr__(self) -> str:
        return (
            f"PipelineConfigManual("
            f"name={self.name!r}, "
            f"source={self.source!r}, "
            f"destination={self.destination!r}, "
            f"parallelism={self.parallelism})"
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, PipelineConfigManual):
            return NotImplemented
        return (
            self.name == other.name
            and self.source == other.source
            and self.destination == other.destination
            and self.parallelism == other.parallelism
        )


# ══════════════════════════════════════════════════════════════════════════════
# PART 2: Same class as a dataclass
#
# @dataclass inspects the class body at DEFINITION TIME (import time) and
# generates the following methods automatically:
#
#   __init__  — one parameter per annotated field, in declaration order.
#               Fields with defaults become keyword arguments.
#   __repr__  — ClassName(field1=value, field2=value, ...)
#   __eq__    — compares all fields, in declaration order.
#
# The class body now reads like a specification:  "what fields does this type
# have?", not "how do I implement all the plumbing for those fields?".
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class PipelineConfig:
    """Dataclass version — identical runtime behaviour, a fraction of the code.

    Each annotated line becomes an __init__ parameter AND a repr field.
    Fields with = defaults work exactly like Python function defaults.
    No field ordering rules beyond: required fields before optional ones.
    """
    name: str
    source: str
    destination: str
    parallelism: int = 4   # default value, just like a parameter default


# ══════════════════════════════════════════════════════════════════════════════
# PART 3: A slightly richer dataclass
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class DatasetMeta:
    """Metadata about a dataset used in a pipeline.

    Demonstrates that @dataclass is compatible with regular methods —
    you can add any business logic alongside the generated boilerplate.
    """
    name: str
    format: str          # e.g. "parquet", "csv", "json"
    row_count: int
    size_mb: float
    is_partitioned: bool = False

    def summary(self) -> str:
        """Human-readable one-liner. A regular method — not generated by @dataclass."""
        partitioned = "partitioned" if self.is_partitioned else "flat"
        return (
            f"{self.name} [{self.format.upper()}] "
            f"— {self.row_count:,} rows, {self.size_mb:.1f} MB, {partitioned}"
        )


def demo_manual_vs_dataclass():
    print("=" * 55)
    print("PART 1 & 2: Manual class vs @dataclass")
    print("=" * 55)

    # Both created the same way — positional args + optional keyword
    manual = PipelineConfigManual("etl_daily", "s3://raw/", "s3://clean/")
    auto = PipelineConfig("etl_daily", "s3://raw/", "s3://clean/")

    # Flow: repr(manual) → PipelineConfigManual.__repr__ (hand-written, 8 lines)
    # Flow: repr(auto)   → PipelineConfig.__repr__   (generated, 0 lines)
    print(f"Manual   repr : {manual!r}")
    print(f"Dataclass repr: {auto!r}")
    print()

    # Both support equality by value
    # Flow: manual == manual2 → PipelineConfigManual.__eq__ (hand-written, 8 lines)
    # Flow: auto   == auto2   → PipelineConfig.__eq__   (generated, 0 lines)
    manual2 = PipelineConfigManual("etl_daily", "s3://raw/", "s3://clean/")
    auto2 = PipelineConfig("etl_daily", "s3://raw/", "s3://clean/")

    print(f"manual == manual2 : {manual == manual2}")
    print(f"auto   == auto2   : {auto == auto2}")
    print()
    print("Same behaviour — but the dataclass required far less code.")


def demo_dataclass_features():
    print("\n" + "=" * 55)
    print("PART 3: Dataclass with methods and defaults")
    print("=" * 55)

    # is_partitioned defaults to False — only ds1 overrides it
    ds1 = DatasetMeta("taxi_trips", "parquet", 1_200_000, 340.5, is_partitioned=True)
    ds2 = DatasetMeta("user_events", "json", 85_000, 12.3)
    ds3 = DatasetMeta("taxi_trips", "parquet", 1_200_000, 340.5, is_partitioned=True)

    # summary() is a hand-written method — @dataclass doesn't generate it
    print(ds1.summary())
    print(ds2.summary())
    print()

    # Generated __repr__ — includes all five fields
    print(f"repr: {ds1!r}")
    print()

    # Generated __eq__ — compares all five fields in declaration order
    # ds1 == ds3: all 5 fields identical → True
    # ds1 == ds2: name, format, row_count, size_mb all differ → False
    print(f"ds1 == ds3 (same data): {ds1 == ds3}")
    print(f"ds1 == ds2 (diff data): {ds1 == ds2}")


def demo_dataclass_inspection():
    print("\n" + "=" * 55)
    print("PART 4: What @dataclass generates")
    print("=" * 55)

    import inspect
    # inspect.signature reads the generated __init__ — shows field names,
    # their types are lost (Python doesn't include annotations in the signature
    # itself), and default values appear exactly as written.
    sig = inspect.signature(PipelineConfig.__init__)
    print(f"Generated __init__ signature: {sig}")
    print()
    print("@dataclass generates:")
    print("  __init__  — positional + keyword args from the field definitions")
    print("  __repr__  — class name + all fields")
    print("  __eq__    — field-by-field comparison")
    print()
    # Important caveat: defining __eq__ in Python causes __hash__ to be set to
    # None. This makes instances unhashable by default (can't put them in a set
    # or use them as dict keys). Use frozen=True to get both __eq__ and __hash__.
    print("It does NOT generate __hash__ by default when __eq__ is defined.")
    print("Add frozen=True or eq=False to control hash behaviour.")


def main():
    demo_manual_vs_dataclass()
    demo_dataclass_features()
    demo_dataclass_inspection()


if __name__ == "__main__":
    main()
